services:
  - type: web
    name: lms-backend
    env: python
    buildCommand: ./build.sh
    startCommand: |
      DJANGO_SETTINGS_MODULE=backend.settings \
      ALLOWED_HOSTS=lms-v1-backend.onrender.com,render.com,.onrender.com,localhost,127.0.0.1 \
      .venv/bin/gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DATABASE_URL
        fromDatabase:
          name: lms_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
    routes:
      - route: lms-backend.onrender.com
        service: lms-backend
        type: http
        port: 8000
