services:
  - type: web
    name: lms-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8000
      # ... other env vars ...
